### ISSUE TITLE
Return 404, rather than error, for unknown component of fixture name

### ISSUE THREAD

**Issue by dsingleton** [alphagov/govuk-component-guide#37]
Looking up a component or fixture key/name that doesn't exist will cause a ruby error.

eg, for:

   http://govuk-component-guide.herokuapp.com/components/titleeee

This is most likely to happen if fixtures are renamed, and a more meaningful 404 should be returned.

**Comment by rubenarakelyan** [comment]
David, I've opened a PR to fix this issue

https://github.com/alphagov/govuk-component-guide/pull/39

**Comment by rubenarakelyan** [comment]
Opened https://github.com/alphagov/govuk-component-guide/pull/40 since I messed up the original when attempting to squash commits

**Comment by rubenarakelyan** [comment]
This has been fixed by https://github.com/alphagov/govuk-component-guide/pull/40
